import { useEffect, useMemo, useState, type ReactNode, type FormEvent } from 'react';
import { QueryClient, QueryClientProvider, useQueryClient } from '@tanstack/react-query';
import { ErrorBoundary } from '@/components/error-boundary';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import { CalendarDays, ChevronLeft, ChevronRight, CircleHelp, Cloud, Download, Images, LogOut, Menu, PanelTop, Settings2, ShieldCheck, X, Heart, Send, Trash2, SlidersHorizontal, Camera } from 'lucide-react';
import { Link, Route, Switch, useLocation } from 'wouter';
import { setBaseUrl, setAuthTokenGetter, getExport, getHealthCheckQueryKey, getGetMembersQueryKey, getGetCurrentSessionQueryKey, getGetMediaQueryKey, getGetCalendarQueryKey, getGetCommentsQueryKey, getGetReactionsQueryKey, getGetStorageQueryKey, getGetMeasurementsQueryKey, useHealthCheck, useGetMembers, useCreateSession, useGetCurrentSession, useDeleteSession, useGetMedia, useGetCalendar, useGetComments, useGetReactions, useCreateComment, useSetReaction, useDeleteReaction, useUpdateMedia, useDeleteMedia, useGetStorage, useGetMeasurements, useCreateMeasurement } from '@workspace/api-client-react';
import type { Member as ApiMember, Photo, CalendarDay, StorageUsage, Measurement } from '@workspace/api-client-react';
import Dashboard from '@/components/Dashboard';
import GhostCamera from '@/components/GhostCamera';
import MemberGallery, { PrivatePhoto } from '@/components/MemberGallery';
import BulkUploader from '@/components/BulkUploader';
import { localDateTimeFromDate, localDateTimeToIso } from '@/lib/dates';

const queryClient = new QueryClient({defaultOptions:{queries:{retry:1,staleTime:25_000}}});
const MEMBER_COLORS:Record<string,string>={ali:'#e8b66d',zakaria:'#79b8a0',idrissa:'#cc8f9b'};
const configuredApiUrl=import.meta.env.VITE_API_BASE_URL?.trim();
setBaseUrl(configuredApiUrl ? new URL(configuredApiUrl).origin : import.meta.env.BASE_URL.replace(/\/+$/, '') || null);
setAuthTokenGetter(()=>localStorage.getItem('souvenirs-session-token'));

function FullLoader(){return <div className="min-h-[100dvh] bg-[#191c25] p-6"><div className="mx-auto max-w-5xl space-y-5"><div className="skeleton h-8 w-40 rounded-lg"/><div className="skeleton h-64 rounded-3xl"/><div className="grid grid-cols-3 gap-4"><div className="skeleton h-32 rounded-2xl"/><div className="skeleton h-32 rounded-2xl"/><div className="skeleton h-32 rounded-2xl"/></div></div></div>}

function Login({members,onLogin,loading,error}:{members:ApiMember[];onLogin:(id:string,pin:string)=>void;loading:boolean;error:string}){
  const [memberId,setMemberId]=useState('');const [pin,setPin]=useState('');
  useEffect(()=>{if(!memberId&&members.length)setMemberId(members[0].id)},[members,memberId]);
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(memberId&&/^\d{6,12}$/.test(pin)&&!loading)onLogin(memberId,pin)};
  return <main className="flex min-h-[100dvh] items-center justify-center bg-[#191c25] px-5 py-10 text-[#eee9df]">
    <div className="w-full max-w-md fade-in">
      <div className="mb-10 flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e8b66d] text-[#191c25]"><Camera size={21}/></div><div><p className="font-serif text-xl font-bold">Souvenirs physiques</p><p className="text-xs text-[#9297a3]">Un album privé, à trois.</p></div></div>
      <section className="panel rounded-3xl p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#e8b66d]">Votre espace partagé</p><h1 className="mt-3 font-serif text-3xl font-semibold">Revenir aux bons jours.</h1><p className="mt-3 text-sm leading-6 text-[#a9acb5]">Choisissez votre profil pour ouvrir l’album sur cet appareil. Votre session sera mémorisée.</p>
        <form onSubmit={submit}>
          <input type="text" name="username" autoComplete="username" value={memberId} readOnly aria-hidden="true" tabIndex={-1} className="sr-only"/>
          <label className="mt-7 block text-xs font-semibold text-[#bdc0c8]">C’est qui ?</label>
          <div className="mt-2 grid grid-cols-3 gap-2">{members.map(m=><button type="button" data-testid={`member-${m.id}`} key={m.id} onClick={()=>setMemberId(m.id)} className={`rounded-xl border px-2 py-3 text-sm transition ${memberId===m.id?'border-[#e8b66d] bg-[#34323a] text-[#f1c886]':'border-[#3a3e49] text-[#a9acb5] hover:bg-[#292d37]'}`}><i className="mx-auto mb-2 block h-2.5 w-2.5 rounded-full" style={{background:m.color||MEMBER_COLORS[m.id]}}/>{m.name}</button>)}</div>
          <label htmlFor="pin" className="mt-5 block text-xs font-semibold text-[#bdc0c8]">Code personnel</label><input id="pin" data-testid="input-pin" type="password" inputMode="numeric" autoComplete="current-password" pattern="[0-9]{6,12}" minLength={6} maxLength={12} value={pin} onChange={e=>setPin(e.target.value)} placeholder="6 à 12 chiffres" className="mt-2 w-full rounded-xl border border-[#3d414d] bg-[#191c25] px-4 py-3.5 text-base tracking-[.25em] outline-none focus:border-[#e8b66d]"/>
          {error&&<p role="alert" className="mt-3 rounded-xl bg-[#492c30] p-3 text-sm text-[#f0b0ac]">{error}</p>}
          <button type="submit" data-testid="button-login" disabled={!memberId||pin.length<6||loading} className="mt-5 w-full rounded-full bg-[#e8b66d] px-5 py-3.5 text-sm font-bold text-[#191c25] hover:bg-[#f1c886] disabled:opacity-40">{loading?'Ouverture de votre album…':'Entrer dans l’album'}</button>
        </form>
        <p className="mt-5 flex items-start gap-2 text-xs leading-5 text-[#858a97]"><ShieldCheck size={15} className="mt-0.5 shrink-0 text-[#79b8a0]"/>Cette session reste sur cet appareil. Les photos et leurs dates se synchronisent dans votre cercle privé.</p>
      </section>
    </div>
  </main>
}

function Shell({member,members,onLogout,children}:{member:ApiMember;members:ApiMember[];onLogout:()=>void;children:ReactNode}){
  const [path]=useLocation();const [mobileOpen,setMobileOpen]=useState(false);
  const nav=[{href:'/',label:'Accueil',icon:PanelTop},{href:'/phototheques',label:'Photothèques',icon:Images},{href:'/calendrier',label:'Calendrier',icon:CalendarDays},{href:'/comparateur',label:'Comparateur',icon:SlidersHorizontal},{href:'/parametres',label:'Paramètres',icon:Settings2}];
  const menu=<><div className="flex items-center gap-3 px-2 pb-8 pt-2"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#e8b66d] text-[#191c25]"><Camera size={19}/></div><div><p className="font-serif font-bold">Souvenirs physiques</p><p className="text-[10px] uppercase tracking-[.14em] text-[#858a97]">Album partagé</p></div></div><p className="mb-3 px-3 text-[10px] font-bold uppercase tracking-[.2em] text-[#666c79]">Votre espace</p><nav className="space-y-1">{nav.map(({href,label,icon:Icon})=><Link key={href} href={href} onClick={()=>setMobileOpen(false)} data-testid={`nav-${label.toLowerCase()}`} className={`nav-link flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium ${path===href?'active':''}`}><Icon size={17}/>{label}</Link>)}</nav><div className="mt-auto pt-8"><div className="mb-4 rounded-xl border border-[#303440] bg-[#1c1f28] p-3"><div className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full" style={{background:member.color||MEMBER_COLORS[member.id]}}/><span className="text-sm font-semibold">{member.name}</span><span className="ml-auto rounded-full bg-[#34483e] px-2 py-1 text-[9px] text-[#92c3a2]">Connecté</span></div><div className="mt-3 flex -space-x-1">{members.map(m=><i key={m.id} className="h-3 w-3 rounded-full border border-[#1c1f28]" title={m.name} style={{background:m.color||MEMBER_COLORS[m.id]}}/>)}</div></div><button onClick={onLogout} className="nav-link flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm"><LogOut size={17}/>Fermer ma session</button></div></>;
  return <div className="shell flex"><aside className="sidebar sticky top-0 hidden h-[100dvh] w-[250px] shrink-0 flex-col px-5 py-6 md:flex">{menu}</aside>{mobileOpen&&<div className="fixed inset-0 z-40 bg-black/70 md:hidden" onClick={()=>setMobileOpen(false)}><aside className="sidebar flex h-full w-[280px] flex-col p-5" onClick={e=>e.stopPropagation()}><button onClick={()=>setMobileOpen(false)} aria-label="Fermer le menu" className="mb-3 self-end text-[#a9acb5]"><X/></button>{menu}</aside></div>}<div className="min-w-0 flex-1"><header className="sticky top-0 z-30 flex h-[68px] items-center justify-between border-b border-[#2b2f3a] bg-[#191c25]/95 px-4 backdrop-blur-md sm:px-7"><button className="text-[#bdc0c8] md:hidden" onClick={()=>setMobileOpen(true)} aria-label="Ouvrir le menu"><Menu/></button><div className="hidden items-center gap-2 text-xs text-[#858a97] sm:flex"><span className="h-1.5 w-1.5 rounded-full bg-[#79b8a0]"/>Un album réservé à votre cercle</div><div className="ml-auto flex items-center gap-2 text-xs text-[#a9acb5]"><i className="h-2.5 w-2.5 rounded-full" style={{background:member.color||MEMBER_COLORS[member.id]}}/> {member.name}</div></header><main className="mx-auto max-w-[1320px] px-4 py-7 sm:px-7 sm:py-9">{children}</main></div></div>
}

function PhotoDetail({photo,members,current,onClose,onChanged}:{photo:Photo;members:ApiMember[];current:ApiMember;onClose:()=>void;onChanged:()=>void}){
  const qc=useQueryClient();const {data:comments,isLoading:commentsLoading,isError:commentsError}=useGetComments(photo.id,{query:{queryKey:getGetCommentsQueryKey(photo.id),enabled:!!photo.id}});
  const createComment=useCreateComment();const setReaction=useSetReaction();const deleteReaction=useDeleteReaction();const update=useUpdateMedia();const remove=useDeleteMedia();
  const [text,setText]=useState('');const [editing,setEditing]=useState(false);const [date,setDate]=useState(localDateTimeFromDate(new Date(photo.takenAt)));const [caption,setCaption]=useState(photo.caption||'');const [message,setMessage]=useState('');
  const reactions=useGetReactions(photo.id,{query:{queryKey:getGetReactionsQueryKey(photo.id),enabled:!!photo.id}});
  const reactionOptions=[{name:'J’aime',value:'\u{1F4AA}'},{name:'Bien vu',value:'\u{1F525}'},{name:'À refaire',value:'\u{1F4C8}'}];
  const comment=async(e:FormEvent)=>{e.preventDefault();if(!text.trim())return;try{await createComment.mutateAsync({id:photo.id,data:{text:text.trim()}});setText('');await qc.invalidateQueries({queryKey:getGetCommentsQueryKey(photo.id)})}catch{setMessage('Le commentaire n’a pas pu être envoyé. Réessayez.')}}
  const toggle=async(_name:string,value:string)=>{try{const mine=reactions.data?.find(reaction=>reaction.emoji===value)?.mine;if(mine)await deleteReaction.mutateAsync({id:photo.id,data:{emoji:value as any}});else await setReaction.mutateAsync({id:photo.id,data:{emoji:value as any}});await qc.invalidateQueries({queryKey:getGetReactionsQueryKey(photo.id)})}catch{setMessage('La réaction n’a pas pu être enregistrée.')}}
  const save=async()=>{try{await update.mutateAsync({id:photo.id,data:{takenAt:localDateTimeToIso(date),caption:caption||null}});setEditing(false);await qc.invalidateQueries({queryKey:getGetMediaQueryKey()});await qc.invalidateQueries({queryKey:getGetCalendarQueryKey()});onChanged()}catch{setMessage('La modification n’a pas été enregistrée.')}}
  const erase=async()=>{if(!window.confirm('Supprimer définitivement cette photo de l’album partagé ?'))return;try{await remove.mutateAsync({id:photo.id});await qc.invalidateQueries({queryKey:getGetMediaQueryKey()});await qc.invalidateQueries({queryKey:getGetCalendarQueryKey()});onClose()}catch{setMessage('La photo n’a pas pu être supprimée.')}}
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/75 p-0 backdrop-blur-sm sm:items-center sm:p-4" onClick={onClose}><section role="dialog" aria-modal="true" aria-label="Détail du souvenir" className="max-h-[94dvh] w-full max-w-4xl overflow-y-auto rounded-t-3xl border border-[#393d49] bg-[#20232d] sm:rounded-3xl" onClick={e=>e.stopPropagation()}><header className="sticky top-0 z-10 flex items-center justify-between border-b border-[#303440] bg-[#20232d]/95 px-4 py-3 backdrop-blur"><p className="text-xs text-[#9297a3]">Pris le <time title={new Date(photo.takenAt).toLocaleString('fr-FR')}>{new Date(photo.takenAt).toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}</time> par {photo.memberName}</p><button aria-label="Fermer" onClick={onClose} className="rounded-full p-2 hover:bg-[#303440]"><X size={18}/></button></header><div className="grid md:grid-cols-[1.2fr_.8fr]"><div className="max-h-[55dvh] min-h-64 bg-[#14161d] md:max-h-[74vh]"><PrivatePhoto id={photo.id} alt={photo.caption||'Photo souvenir'}/></div><div className="space-y-5 p-5">
    <div><h2 className="font-serif text-xl font-semibold">{photo.caption||'Un moment partagé'}</h2><p className="mt-1 text-xs text-[#9297a3]">{new Date(photo.takenAt).toLocaleString('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit'})}</p></div>
    <div className="flex flex-wrap gap-2">{reactionOptions.map(r=>{const reaction=reactions.data?.find(item=>item.emoji===r.value);return <button key={r.name} aria-pressed={reaction?.mine||false} onClick={()=>toggle(r.name,r.value)} className={`rounded-full border px-3 py-1.5 text-xs ${reaction?.mine?'border-[#e8b66d] bg-[#3b3428] text-[#f1c886]':'border-[#444854] text-[#bdc0c8]'}`}>{r.name}{reaction?.count?` · ${reaction.count}`:''}</button>})}</div>
    <div><h3 className="mb-3 text-xs font-bold uppercase tracking-[.15em] text-[#9297a3]">Petits mots</h3>{commentsLoading?<div className="skeleton h-14 rounded-xl"/>:commentsError?<p className="text-xs text-[#e4a19c]">Les commentaires sont indisponibles.</p>:comments?.length?<div className="max-h-40 space-y-3 overflow-y-auto">{comments.map(c=><div key={c.id} className="rounded-xl bg-[#191c25] p-3"><p className="text-xs font-semibold" style={{color:members.find(m=>m.id===c.memberId)?.color}}>{c.memberName}</p><p className="mt-1 text-sm text-[#d0cdd0]">{c.text}</p></div>)}</div>:<p className="text-sm text-[#9297a3]">Pas encore de commentaire. Laissez le premier mot.</p>}
    <form onSubmit={comment} className="mt-3 flex gap-2"><input aria-label="Votre commentaire" value={text} maxLength={500} onChange={e=>setText(e.target.value)} placeholder="Écrire un petit mot…" className="min-w-0 flex-1 rounded-xl border border-[#3b3f4a] bg-[#191c25] px-3 py-2.5 text-sm"/><button disabled={!text.trim()||createComment.isPending} aria-label="Envoyer le commentaire" className="rounded-xl bg-[#e8b66d] px-3 text-[#191c25] disabled:opacity-40"><Send size={16}/></button></form></div>
    {current.id===photo.memberId&&<><div className="flex flex-wrap items-center justify-between gap-2 border-t border-[#303440] pt-4"><button onClick={()=>setEditing(!editing)} className="text-xs font-semibold text-[#e8b66d]">Corriger les détails</button><button onClick={erase} aria-label="Supprimer la photo" className="flex items-center gap-1 text-xs text-[#dc938f]"><Trash2 size={14}/>Supprimer</button></div>
    {editing&&<div className="space-y-3 rounded-xl bg-[#191c25] p-3"><label className="block text-xs text-[#a9acb5]">Date réelle de prise<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)} className="mt-1 w-full rounded-lg border border-[#3b3f4a] bg-[#252832] px-3 py-2 text-sm"/></label><label className="block text-xs text-[#a9acb5]">Légende<input maxLength={500} value={caption} onChange={e=>setCaption(e.target.value)} className="mt-1 w-full rounded-lg border border-[#3b3f4a] bg-[#252832] px-3 py-2 text-sm"/></label><button onClick={save} disabled={update.isPending} className="rounded-full bg-[#e8b66d] px-4 py-2 text-xs font-bold text-[#191c25]">{update.isPending?'Enregistrement…':'Enregistrer'}</button></div>}</>}
    {message&&<p role="alert" className="text-xs text-[#e4a19c]">{message}</p>}
  </div></div></section></div>
}

function AppContent(){
  const qc=useQueryClient();const [,navigate]=useLocation();const token=localStorage.getItem('souvenirs-session-token');
  const health=useHealthCheck({query:{queryKey:getHealthCheckQueryKey()}});
  const membersQuery=useGetMembers({query:{queryKey:getGetMembersQueryKey()}});
  const members=(membersQuery.data||[]).map(m=>({...m,color:m.color||MEMBER_COLORS[m.id]}));
  const currentQuery=useGetCurrentSession({query:{queryKey:getGetCurrentSessionQueryKey(),enabled:!!token}});
  const session=currentQuery.data;
  const [loginError,setLoginError]=useState('');const create=useCreateSession({mutation:{onSuccess:(data)=>{localStorage.setItem('souvenirs-session-token',data.token);qc.clear();qc.setQueryData(getGetCurrentSessionQueryKey(),data.member);navigate('/')}}});
  const logoutMutation=useDeleteSession();
  const [uploadOpen,setUploadOpen]=useState(false);const [selected,setSelected]=useState<Photo|null>(null);
  const media=useGetMedia({limit:200},{query:{queryKey:getGetMediaQueryKey({limit:200}),enabled:!!session}});
  const allPhotos=media.data||[];
  const logout=async()=>{try{await logoutMutation.mutateAsync()}catch{/* La session locale doit pouvoir être fermée hors ligne. */}localStorage.removeItem('souvenirs-session-token');qc.clear();navigate('/')}
  if(membersQuery.isLoading||token&&currentQuery.isLoading)return <FullLoader/>;
  if(!session)return <Login members={members} loading={create.isPending} error={loginError|| (membersQuery.isError?'Impossible de charger les profils. Vérifiez la connexion.':'')} onLogin={(id,pin)=>{setLoginError('');create.mutate({data:{memberId:id as any,pin}},{onError:()=>setLoginError('Profil ou code incorrect. Réessayez.')})}}/>;
  const shared={member:session,members,onLogout:logout};
  return <>
    <Shell {...shared}><Switch>
      <Route path="/" component={()=> <HomePage {...shared} photos={allPhotos} loading={media.isLoading} error={media.isError} onRetry={()=>media.refetch()} onUpload={()=>setUploadOpen(true)}/>}/>
      <Route path="/phototheques" component={()=> <GalleryPage {...shared} photos={allPhotos} loading={media.isLoading} error={media.isError} onRetry={()=>media.refetch()} onPhoto={setSelected} onUpload={()=>setUploadOpen(true)}/>}/>
      <Route path="/calendrier" component={()=> <CalendarPage {...shared} onDay={(date)=>navigate(`/phototheques?date=${date}`)} onPhoto={setSelected} />}/>
      <Route path="/comparateur" component={()=> <ComparePage {...shared} photos={allPhotos} onUpload={()=>setUploadOpen(true)}/>}/>
      <Route path="/parametres" component={()=> <SettingsPage {...shared} photos={allPhotos} onLogout={logout}/>}/>
      <Route><NotFoundPage/></Route>
    </Switch></Shell>
    <BulkUploader open={uploadOpen} onClose={()=>setUploadOpen(false)} member={session} members={members} ghostPhoto={[...allPhotos].sort((a,b)=>new Date(b.takenAt).getTime()-new Date(a.takenAt).getTime())[0]}/>
    {selected&&<PhotoDetail photo={selected} members={members} current={session} onClose={()=>setSelected(null)} onChanged={()=>{}}/>}
    <span className="sr-only" aria-live="polite">{health.isError?'Le service est momentanément indisponible.':health.data?.status==='ok'?'Service disponible':''}</span>
  </>
}

function PageTitle({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:ReactNode}){return <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#e8b66d]">{eyebrow}</p><h1 className="mt-2 font-serif text-3xl font-semibold sm:text-4xl">{title}</h1><p className="mt-2 max-w-xl text-sm leading-6 text-[#9297a3]">{description}</p></div>{action}</div>}
function HomePage({member,members,photos,loading,error,onRetry,onUpload}:{member:ApiMember;members:ApiMember[];photos:Photo[];loading:boolean;error:boolean;onRetry:()=>void;onUpload:()=>void}){return <>{error?<ErrorPanel onRetry={onRetry}/>:loading?<FullContentSkeleton/>:<Dashboard photos={photos} members={members} onUpload={onUpload}/>}</>}
function FullContentSkeleton(){return <div className="space-y-5"><div className="skeleton h-64 rounded-[28px]"/><div className="grid gap-4 md:grid-cols-2"><div className="skeleton h-48 rounded-2xl"/><div className="skeleton h-48 rounded-2xl"/></div></div>}
function ErrorPanel({onRetry}:{onRetry:()=>void}){return <div role="alert" className="panel rounded-2xl p-8 text-center"><CircleHelp className="mx-auto text-[#e8b66d]"/><h2 className="mt-3 font-semibold">L’album ne répond pas.</h2><p className="mt-2 text-sm text-[#9297a3]">Votre session est conservée. Réessayez dans un instant.</p><button onClick={onRetry} className="mt-5 rounded-full border border-[#545965] px-4 py-2 text-sm">Réessayer</button></div>}
function GalleryPage({members,member,photos,loading,error,onRetry,onPhoto,onUpload}:{members:ApiMember[];member:ApiMember;photos:Photo[];loading:boolean;error:boolean;onRetry:()=>void;onPhoto:(p:Photo)=>void;onUpload:()=>void}){
  const [filter,setFilter]=useState('tout');const [search,setSearch]=useState('');const [sortOrder,setSortOrder]=useState<'recent'|'older'>('recent');
  const params=new URLSearchParams(window.location.search);const date=params.get('date');
  const shown=useMemo(()=>photos.filter(p=>(filter==='tout'||p.memberId===filter||(p.taggedMemberIds||[]).includes(filter as Photo['memberId']))&&(!date||p.takenAt.slice(0,10)===date)&&(!search||`${p.caption||''} ${p.memberName}`.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>{
    const delta = new Date(b.takenAt).getTime() - new Date(a.takenAt).getTime();
    return sortOrder === 'recent' ? delta : -delta;
  }),[photos,filter,date,search,sortOrder]);
  return <><PageTitle eyebrow="Les archives" title="Photothèques" description={date?`Les souvenirs du ${new Date(`${date}T12:00:00`).toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}.`:'Toutes vos photos partagées, classées par date de prise.'} action={<button onClick={onUpload} className="rounded-full bg-[#e8b66d] px-4 py-2.5 text-sm font-bold text-[#191c25]">Ajouter des photos</button>}/>
    <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center"><div className="flex flex-wrap gap-2"><button onClick={()=>setFilter('tout')} className={`rounded-full border px-3 py-2 text-xs ${filter==='tout'?'border-[#e8b66d] bg-[#3b3428] text-[#f1c886]':'border-[#414550] text-[#a9acb5]'}`}>Tout le groupe</button>{members.map(m=><button key={m.id} onClick={()=>setFilter(m.id)} className={`flex items-center gap-2 rounded-full border px-3 py-2 text-xs ${filter===m.id?'border-[#e8b66d] bg-[#3b3428] text-[#f1c886]':'border-[#414550] text-[#a9acb5]'}`}><i className="h-2 w-2 rounded-full" style={{background:m.color||MEMBER_COLORS[m.id]}}/>{m.name}</button>)}</div><div className="ml-auto flex w-full flex-col gap-2 sm:max-w-md sm:flex-row"><div className="flex items-center rounded-xl border border-[#3a3e49] bg-[#20232d] p-1 text-xs"><button onClick={()=>setSortOrder('recent')} className={`rounded-lg px-3 py-2 ${sortOrder==='recent'?'bg-[#3b3428] text-[#f1c886]':'text-[#a9acb5]'}`}>Plus récents</button><button onClick={()=>setSortOrder('older')} className={`rounded-lg px-3 py-2 ${sortOrder==='older'?'bg-[#3b3428] text-[#f1c886]':'text-[#a9acb5]'}`}>Plus anciens</button></div><input aria-label="Rechercher une légende" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher une légende…" className="w-full rounded-xl border border-[#3a3e49] bg-[#20232d] px-4 py-2.5 text-sm"/></div></div>
    {error?<ErrorPanel onRetry={onRetry}/>:loading?<div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{Array.from({length:8},(_,i)=><div key={i} className="skeleton aspect-[4/5] rounded-xl"/>)}</div>:shown.length?<MemberGallery photos={shown} members={members} onSelect={onPhoto}/>:<div className="space-y-4"><div className="panel rounded-2xl px-6 py-8 text-center"><h3 className="font-semibold">Aucun souvenir dans cette vue</h3><p className="mx-auto mt-2 max-w-md text-sm text-[#9297a3]">{date?'Aucune photo n’a été prise à cette date. Choisissez une autre date ou ajoutez un souvenir historique.':'Choisissez un autre membre ou ajoutez la première photo de cette galerie.'}</p></div><GhostCamera onClick={onUpload} label="Ajouter le premier souvenir"/></div>}
    {!loading&&!error&&shown.length>0&&<p className="mt-4 text-xs text-[#858a97]">{shown.length} souvenir{shown.length>1?'s':''} · trié par {sortOrder==='recent'?'plus récents':'plus anciens'}</p>}
  </>
}

function CalendarPage({members,onDay,onPhoto}:{members:ApiMember[];onDay:(date:string)=>void;onPhoto:(p:Photo)=>void}){
  const [year,setYear]=useState(new Date().getFullYear());const [mode,setMode]=useState<'année'|'mois'>('année');const [month,setMonth]=useState(new Date().getMonth());
  const cal=useGetCalendar({year},{query:{queryKey:getGetCalendarQueryKey({year})}});
  const map=useMemo(()=>new Map((cal.data||[]).map((d:CalendarDay)=>[d.date,d])),[cal.data]);
  const months=mode==='mois'?[month]:Array.from({length:12},(_,i)=>i);
  const dayNames=['L','M','M','J','V','S','D'];
  const today = new Date();
  const todayKey = `${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
  return <><PageTitle eyebrow="Le fil du temps" title="Calendrier" description="Chaque jour reste à sa place. Les dates sans photo sont visibles, pas effacées."/>
    <div className="panel mb-6 flex flex-wrap items-center justify-between gap-3 rounded-2xl p-4"><div className="flex items-center gap-2"><button aria-label="Année précédente" onClick={()=>setYear(y=>y-1)} className="rounded-lg p-2 hover:bg-[#303440]"><ChevronLeft size={18}/></button><span className="min-w-14 text-center font-serif text-xl font-semibold">{year}</span><button aria-label="Année suivante" onClick={()=>setYear(y=>y+1)} className="rounded-lg p-2 hover:bg-[#303440]"><ChevronRight size={18}/></button></div><div className="flex items-center gap-1 rounded-full bg-[#191c25] p-1"><button onClick={()=>setMode('année')} className={`rounded-full px-4 py-2 text-xs ${mode==='année'?'bg-[#414550] text-[#eee9df]':'text-[#9297a3]'}`}>Année</button><button onClick={()=>setMode('mois')} className={`rounded-full px-4 py-2 text-xs ${mode==='mois'?'bg-[#414550] text-[#eee9df]':'text-[#9297a3]'}`}>Mois</button></div>{mode==='mois'&&<select aria-label="Choisir le mois" value={month} onChange={e=>setMonth(Number(e.target.value))} className="rounded-lg border border-[#3a3e49] bg-[#191c25] px-3 py-2 text-sm">{Array.from({length:12},(_,i)=><option key={i} value={i}>{new Date(year,i,1).toLocaleDateString('fr-FR',{month:'long'})}</option>)}</select>}</div>
    {cal.isError?<ErrorPanel onRetry={()=>cal.refetch()}/>:cal.isLoading?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Array.from({length:6},(_,i)=><div key={i} className="skeleton h-64 rounded-2xl"/>)}</div>:<div className={`grid gap-4 ${mode==='année'?'sm:grid-cols-2 lg:grid-cols-3':'max-w-2xl'}`}>{months.map(m=>{const first=new Date(year,m,1),offset=(first.getDay()+6)%7,total=new Date(year,m+1,0).getDate();return <section key={m} className="panel rounded-2xl p-4"><h2 className="mb-4 font-serif text-lg font-semibold capitalize">{first.toLocaleDateString('fr-FR',{month:'long'})}</h2><div className="mb-2 grid grid-cols-7 text-center text-[10px] text-[#747a87]">{dayNames.map((n,i)=><span key={i}>{n}</span>)}</div><div className="grid grid-cols-7 gap-y-1">{Array.from({length:offset},(_,i)=><span key={`blank-${i}`} className="h-9"/>)}
        {Array.from({length:total},(_,i)=>{const d=i+1,dayKey=`${year}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,record=map.get(dayKey) as CalendarDay|undefined,has=!!record?.photoCount,isToday=dayKey===todayKey;return <button key={dayKey} onClick={()=>onDay(dayKey)} aria-label={`${d} ${first.toLocaleDateString('fr-FR',{month:'long'})}, ${record?.photoCount||0} photo${record?.photoCount===1?'':'s'}`} className={`relative mx-auto grid h-9 w-9 place-items-center rounded-full text-xs transition ${isToday?'bg-[#e8b66d] font-bold text-[#191c25] shadow-[0_0_0_2px_rgba(232,182,109,0.28)]':has?'bg-[#33323a] font-semibold text-[#f1c886] hover:bg-[#48413a]':'text-[#666c79] hover:bg-[#303440] hover:text-[#d7d2c8]'}`}>{d}{has&&<span className="absolute -bottom-0.5 flex gap-0.5">{record!.memberIds.slice(0,3).map(id=><i key={id} className="h-1 w-1 rounded-full" style={{background:members.find(mm=>mm.id===id)?.color||MEMBER_COLORS[id]}}/>)}</span>}</button>})}
      </div></section>})}</div>}
    <p className="mt-5 text-xs text-[#858a97]">Sélectionnez un jour, même vide, pour ouvrir sa galerie. Les points indiquent les membres présents et le jour actuel est mis en évidence.</p>
  </>
}

function ComparePage({photos,onUpload}:{members:ApiMember[];member:ApiMember;onLogout:()=>void;photos:Photo[];onUpload:()=>void}){
  const [a,setA]=useState('');const [b,setB]=useState('');const [opacity,setOpacity]=useState(50);const first=photos.find(p=>p.id===a),second=photos.find(p=>p.id===b);
  return <><PageTitle eyebrow="Deux instants" title="Comparateur" description="Superposez deux images pour retrouver un angle, un lieu ou une ressemblance."/>
    {photos.length<2?<div className="panel rounded-2xl p-8 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[#303440] text-[#e8b66d]"><Images/></div><h2 className="mt-4 font-semibold">Deux photos pour commencer</h2><p className="mx-auto mt-2 max-w-sm text-sm text-[#9297a3]">Ajoutez au moins deux souvenirs. Ensuite, choisissez les images et ajustez leur superposition.</p><button onClick={onUpload} className="mt-5 rounded-full bg-[#e8b66d] px-5 py-3 text-sm font-bold text-[#191c25]">Ajouter une photo</button></div>:
    <div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><section className="panel space-y-5 rounded-2xl p-5"><label className="block text-xs font-semibold text-[#a9acb5]">Première photo<select value={a} onChange={e=>setA(e.target.value)} className="mt-2 w-full rounded-xl border border-[#414550] bg-[#191c25] p-3 text-sm">{[<option value="" key="none">Choisir une photo</option>,...photos.map(p=><option key={p.id} value={p.id}>{p.memberName} · {new Date(p.takenAt).toLocaleDateString('fr-FR')}</option>)]}</select></label><label className="block text-xs font-semibold text-[#a9acb5]">Deuxième photo<select value={b} onChange={e=>setB(e.target.value)} className="mt-2 w-full rounded-xl border border-[#414550] bg-[#191c25] p-3 text-sm">{[<option value="" key="none">Choisir une photo</option>,...photos.map(p=><option key={p.id} value={p.id}>{p.memberName} · {new Date(p.takenAt).toLocaleDateString('fr-FR')}</option>)]}</select></label><label className="block text-xs font-semibold text-[#a9acb5]">Opacité de la deuxième photo <span className="float-right text-[#e8b66d]">{opacity}%</span><input type="range" min="0" max="100" value={opacity} onChange={e=>setOpacity(Number(e.target.value))} className="mt-3 w-full accent-[#e8b66d]"/></label><p className="text-xs leading-5 text-[#858a97]">Choisissez deux prises de vue différentes, puis faites glisser le curseur pour les comparer.</p></section>
    <div className="relative aspect-[4/3] overflow-hidden rounded-2xl border border-[#363a45] bg-[#14161d]">{first?<PrivatePhoto id={first.id} alt="Première photo comparée"/>:<div className="grid h-full place-items-center text-sm text-[#737987]">La première image apparaîtra ici</div>}{second&&<div className="absolute inset-0" style={{opacity:opacity/100}}><PrivatePhoto id={second.id} alt="Deuxième photo superposée"/></div>}<div className="absolute bottom-3 left-3 right-3 flex justify-between gap-3">{first&&<span className="max-w-[48%] truncate rounded-full bg-[#191c25]/85 px-3 py-2 text-xs">{new Date(first.takenAt).toLocaleDateString('fr-FR')}</span>}{second&&<span className="ml-auto max-w-[48%] truncate rounded-full bg-[#191c25]/85 px-3 py-2 text-xs">{new Date(second.takenAt).toLocaleDateString('fr-FR')}</span>}</div></div></div>}
  </>
}

function SettingsPage({member,members,photos,onLogout}:{member:ApiMember;members:ApiMember[];photos:Photo[];onLogout:()=>void}){
  const qc=useQueryClient();
  const storage=useGetStorage({query:{queryKey:getGetStorageQueryKey()}});const percent=storage.data?Math.min(100,storage.data.usedBytes/Math.max(1,storage.data.limitBytes)*100):0;
  const measurements=useGetMeasurements({memberId:member.id},{query:{queryKey:getGetMeasurementsQueryKey({memberId:member.id})}});
  const createMeasurement=useCreateMeasurement();
  const [measuredAt,setMeasuredAt]=useState(localDateTimeFromDate(new Date()));
  const [measurementValues,setMeasurementValues]=useState({weightKg:'',armCm:'',chestCm:'',waistCm:'',thighCm:''});
  const [measurementMessage,setMeasurementMessage]=useState('');
  const measurementFields=[
    {key:'weightKg' as const,label:'Poids',unit:'kg',max:500},
    {key:'armCm' as const,label:'Bras',unit:'cm',max:200},
    {key:'chestCm' as const,label:'Poitrine',unit:'cm',max:300},
    {key:'waistCm' as const,label:'Taille',unit:'cm',max:300},
    {key:'thighCm' as const,label:'Cuisse',unit:'cm',max:200},
  ];
  const saveMeasurement=async(event:FormEvent<HTMLFormElement>)=>{
    event.preventDefault();setMeasurementMessage('');
    const values:Record<string,number>={};
    for(const field of measurementFields){
      const raw=measurementValues[field.key].trim();
      if(!raw)continue;
      const value=Number(raw);
      if(!Number.isFinite(value)||value<=0||value>field.max){setMeasurementMessage(`Valeur invalide pour « ${field.label} » (maximum ${field.max} ${field.unit}).`);return}
      values[field.key]=value;
    }
    if(!Object.keys(values).length){setMeasurementMessage('Ajoutez au moins une valeur, ou laissez cette section vide.');return}
    try{
      await createMeasurement.mutateAsync({data:{memberId:member.id,measuredAt:localDateTimeToIso(measuredAt),...values}});
      await qc.invalidateQueries({queryKey:getGetMeasurementsQueryKey({memberId:member.id})});
      setMeasurementValues({weightKg:'',armCm:'',chestCm:'',waistCm:'',thighCm:''});
      setMeasuredAt(localDateTimeFromDate(new Date()));
      setMeasurementMessage('Mensurations enregistrées sur votre profil.');
    }catch{setMeasurementMessage('Les mensurations n’ont pas été enregistrées. Réessayez.')}
  };
  const fmt=(b:number)=>b<1024*1024?`${(b/1024).toFixed(0)} Ko`:`${(b/1024/1024).toFixed(1)} Mo`;
  const [exportError,setExportError]=useState('');const [exporting,setExporting]=useState(false);
  const download=async()=>{setExportError('');setExporting(true);try{const data=await getExport();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='souvenirs-physiques-export.json';a.click();URL.revokeObjectURL(url)}catch{setExportError('L’export n’a pas pu être préparé. Réessayez.')}finally{setExporting(false)}};
  return <><PageTitle eyebrow="Votre appareil" title="Paramètres" description="Gérez la session locale et gardez une copie lisible des informations de votre album."/>
    <div className="grid gap-4 lg:grid-cols-2"><section className="panel rounded-2xl p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#303440] text-[#e8b66d]"><ShieldCheck size={19}/></span><div><h2 className="font-semibold">Session sur cet appareil</h2><p className="text-xs text-[#858a97]">La session est privée et mémorisée localement.</p></div></div><div className="mt-5 flex items-center gap-3 rounded-xl bg-[#191c25] p-4"><i className="h-3 w-3 rounded-full" style={{background:member.color||MEMBER_COLORS[member.id]}}/><span className="text-sm">{member.name}</span><span className="ml-auto text-xs text-[#79b8a0]">Session active</span></div><div className="mt-3 flex gap-2">{members.filter(m=>m.id!==member.id).map(m=><span key={m.id} className="rounded-full border border-[#3b3f4a] px-3 py-1.5 text-xs text-[#a9acb5]">{m.name}</span>)}</div><button onClick={onLogout} className="mt-5 flex items-center gap-2 rounded-full border border-[#555965] px-4 py-2.5 text-sm text-[#e3a19c] hover:bg-[#492c30]"><LogOut size={15}/>Fermer ma session ici</button></section>
    <section className="panel rounded-2xl p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#303440] text-[#79b8a0]"><Cloud size={19}/></span><div><h2 className="font-semibold">Stockage de l’album</h2><p className="text-xs text-[#858a97]">Espace utilisé par les images partagées.</p></div></div>{storage.isLoading?<div className="skeleton mt-6 h-16 rounded-xl"/>:storage.isError?<div className="mt-5 rounded-xl bg-[#492c30] p-3 text-sm text-[#f0b0ac]"><p>La capacité de stockage est indisponible.</p><button onClick={()=>storage.refetch()} className="mt-2 underline">Réessayer</button></div>:<><div className="mt-6 flex items-baseline justify-between"><span className="font-serif text-2xl font-semibold">{fmt((storage.data as StorageUsage).usedBytes)}</span><span className="text-xs text-[#9297a3]">sur {fmt((storage.data as StorageUsage).limitBytes)}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-[#363a45]"><div className="h-full rounded-full bg-[#79b8a0] transition-all" style={{width:`${percent}%`}}/></div><p className="mt-3 text-xs text-[#858a97]">{percent.toFixed(0)} % occupé · Les images sont partagées entre les membres.</p></>}</section>
    <section className="panel rounded-2xl p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#303440] text-[#e8b66d]"><Download size={19}/></span><div><h2 className="font-semibold">Exporter les informations</h2><p className="text-xs text-[#858a97]">Télécharger les dates, légendes et interactions au format JSON.</p></div></div><p className="mt-4 text-sm leading-6 text-[#a9acb5]">L’export contient toutes les métadonnées de l’album. Les fichiers image ne sont pas inclus.</p>{exportError&&<p role="alert" className="mt-3 text-xs text-[#e4a19c]">{exportError}</p>}<button disabled={exporting} onClick={download} className="mt-4 rounded-full border border-[#555965] px-4 py-2.5 text-sm hover:border-[#e8b66d] disabled:opacity-50">{exporting?'Préparation…':'Télécharger l’export'}</button></section>
    <section className="panel rounded-2xl p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#303440] text-[#cc8f9b]"><Heart size={19}/></span><div><h2 className="font-semibold">Un album, trois regards</h2><p className="text-xs text-[#858a97]">Les membres de votre cercle</p></div></div><div className="mt-5 space-y-3">{members.map(m=><div key={m.id} className="flex items-center gap-3"><i className="h-3 w-3 rounded-full" style={{background:m.color||MEMBER_COLORS[m.id]}}/><span className="text-sm">{m.name}</span>{m.id===member.id&&<span className="ml-auto text-[10px] text-[#e8b66d]">Vous</span>}</div>)}</div></section>
    <section className="panel rounded-2xl p-5 sm:p-6 lg:col-span-2"><div><h2 className="font-semibold">Mensurations facultatives</h2><p className="mt-1 text-xs text-[#858a97]">Quelques repères datés, privés à votre profil. Rien n’est requis et aucune séance n’est suivie.</p></div>
      <form onSubmit={saveMeasurement} className="mt-5 space-y-4"><label className="block text-xs text-[#a9acb5]">Date<input type="datetime-local" value={measuredAt} onChange={event=>setMeasuredAt(event.target.value)} className="mt-1 w-full rounded-lg border border-[#3b3f4a] bg-[#191c25] px-3 py-2 text-sm sm:max-w-xs"/></label>
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{measurementFields.map(field=><label key={field.key} className="block text-xs text-[#a9acb5]">{field.label} ({field.unit})<input type="number" min="0" max={field.max} step="0.1" inputMode="decimal" value={measurementValues[field.key]} onChange={event=>setMeasurementValues(current=>({...current,[field.key]:event.target.value}))} className="mt-1 w-full rounded-lg border border-[#3b3f4a] bg-[#191c25] px-3 py-2 text-sm"/></label>)}</div>
        <button type="submit" disabled={createMeasurement.isPending} className="rounded-full border border-[#555965] px-4 py-2.5 text-sm hover:border-[#e8b66d] disabled:opacity-50">{createMeasurement.isPending?'Enregistrement…':'Enregistrer un repère'}</button>
        {measurementMessage&&<p role="status" className="text-xs text-[#a9acb5]">{measurementMessage}</p>}
      </form>
      {measurements.isError?<p role="alert" className="mt-5 text-sm text-[#e4a19c]">Votre historique de mensurations est indisponible.</p>:measurements.isLoading?<div className="skeleton mt-5 h-16 rounded-xl"/>:measurements.data?.length?<div className="mt-6 space-y-3">{measurements.data.map((entry:Measurement)=><div key={entry.id} className="rounded-xl bg-[#191c25] p-4"><time className="text-xs text-[#e8b66d]">{new Date(entry.measuredAt).toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}</time><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-[#bdc0c8]">{measurementFields.map(field=>{const value=entry[field.key];return value===null||value===undefined?null:<span key={field.key}>{field.label} : {value} {field.unit}</span>})}</div></div>)}</div>:<p className="mt-5 text-sm text-[#9297a3]">Aucun repère ajouté. Cette section peut rester vide.</p>}
    </section></div>
  </>
}
function NotFoundPage(){return <div className="panel rounded-3xl p-10 text-center"><h1 className="font-serif text-3xl">Cette page n’existe pas.</h1><p className="mt-2 text-sm text-[#9297a3]">Revenez à votre album partagé.</p><Link href="/" className="mt-5 inline-block text-sm text-[#e8b66d]">Retour à l’accueil</Link></div>}

function App(){return <QueryClientProvider client={queryClient}><TooltipProvider><ErrorBoundary><AppContent/></ErrorBoundary><Toaster/></TooltipProvider></QueryClientProvider>}
export default App;