import { ArrowRight, CalendarDays, Images, Sparkles } from 'lucide-react';
import { Link } from 'wouter';
import { PrivatePhoto, relativeTakenAt } from './MemberGallery';

export default function Dashboard({ photos, members, onUpload }: {photos:any[];members:any[];onUpload:()=>void}) {
  const latest=[...photos].sort((a,b)=>new Date(b.takenAt).getTime()-new Date(a.takenAt).getTime()).slice(0,6);
  const last=latest[0];
  const byMonth=new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(new Date());
  return <div className="fade-in space-y-8">
    <section className="relative overflow-hidden rounded-[28px] border border-[#383b46] bg-[#242833] px-6 py-8 sm:px-10 sm:py-11">
      <div className="absolute -right-12 -top-28 h-72 w-72 rounded-full border border-[#484b55] opacity-40"/><div className="absolute -right-1 top-4 h-40 w-40 rounded-full border border-[#484b55] opacity-30"/>
      <div className="relative max-w-xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#e8b66d]">Un album à trois</p><h1 className="mt-4 font-serif text-4xl font-semibold leading-[1.08] tracking-tight sm:text-6xl">Les jours qu’on<br/><span className="text-[#e8b66d]">veut garder.</span></h1><p className="mt-5 max-w-md text-sm leading-6 text-[#b1b3bc]">Vos moments, vos dates, votre petit cercle. Un endroit privé pour revoir l’histoire telle qu’elle s’est passée.</p><button onClick={onUpload} className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#e8b66d] px-5 py-3 text-sm font-bold text-[#191c25] transition hover:bg-[#f1c886]">Ajouter un souvenir <ArrowRight size={16}/></button></div>
      <div className="relative mt-8 flex items-center gap-3">{members.map(m=><div key={m.id} title={m.name} className="flex items-center gap-2 rounded-full border border-[#484b55] bg-[#1c1f28] px-3 py-2 text-xs"><i className="h-2.5 w-2.5 rounded-full" style={{background:m.color}}/>{m.name}</div>)}</div>
    </section>
    <div className="grid gap-4 md:grid-cols-[1.25fr_.75fr]">
      <section className="panel flex min-h-[230px] flex-col justify-between rounded-2xl p-5 sm:p-6"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[.16em] text-[#9297a3]">Repère du moment</p><h2 className="mt-2 font-serif text-2xl font-semibold">{last?new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'long',year:'numeric'}).format(new Date(last.takenAt)):'Votre première date'}</h2></div><span className="rounded-full bg-[#303440] p-2.5 text-[#e8b66d]"><Sparkles size={17}/></span></div><p title={last?new Date(last.takenAt).toLocaleString('fr-FR'):undefined} className="mt-4 text-sm text-[#a9acb5]">{last?`${last.caption||`Une photo de ${last.memberName}`} · ${relativeTakenAt(last.takenAt)}`:'Les souvenirs apparaîtront ici dès le premier ajout.'}</p><Link href="/calendrier" className="mt-5 flex items-center gap-2 text-sm font-semibold text-[#e8b66d]">Parcourir le calendrier <ArrowRight size={15}/></Link></section>
      <section className="panel flex flex-col justify-between rounded-2xl p-5 sm:p-6"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[.16em] text-[#9297a3]">Ce mois-ci</p><h2 className="mt-2 font-serif text-2xl font-semibold capitalize">{byMonth}</h2></div><CalendarDays className="text-[#e8b66d]"/></div><p className="mt-5 text-sm text-[#a9acb5]">{photos.length?`${photos.length} souvenir${photos.length>1?'s':''} dans l’album chargé.`:'Les jours vides restent dans le calendrier, prêts à accueillir vos images.'}</p><Link href="/phototheques" className="mt-5 flex items-center gap-2 text-sm font-semibold text-[#e8b66d]">Ouvrir les photothèques <Images size={15}/></Link></section>
    </div>
    <section><div className="mb-4 flex items-end justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-[#9297a3]">Déjà dans l’album</p><h2 className="mt-1 font-serif text-2xl font-semibold">Souvenirs récents</h2></div><Link href="/phototheques" className="text-sm text-[#e8b66d]">Tout voir</Link></div>
      {latest.length?<div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{latest.map(p=><Link href="/phototheques" key={p.id} className="photo-card aspect-[4/5] rounded-xl"><PrivatePhoto id={p.id} alt={p.caption||'Souvenir partagé'}/><span className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 to-transparent p-3 pt-9 text-xs">{new Date(p.takenAt).toLocaleDateString('fr-FR',{day:'numeric',month:'short'})}</span></Link>)}</div>:<div className="panel rounded-2xl p-7 text-center"><p className="text-sm font-semibold">Votre album est encore à écrire.</p><p className="mt-2 text-sm text-[#9297a3]">Les photos importées ici se retrouveront aussi dans le calendrier et les galeries de chacun.</p></div>}
    </section>
  </div>
}